In [2]:
from fredapi import Fred
import pandas as pd
import yfinance as yf
import os 
from dotenv import load_dotenv

In [3]:
fred_api_key = os.getenv('API_FRED')
fred = Fred(api_key=fred_api_key)

In [ ]:
#Downloading 2y T-Note
get_t_note_2y = fred.get_series('DGS2')

In [ ]:
#Getting it into a dataframe
t_note_2y = pd.DataFrame(get_t_note_2y, columns=['Close'])
t_note_2y.index.name = 'Date'
t_note_2y.head()

t_note_2y.to_csv('US02Y.csv')

In [ ]:
#Downloading S&P500 
get_sp500 = yf.download('^GSPC', start='1985-01-01')

[*********************100%***********************]  1 of 1 completed

In [ ]:
#Cleaning data and getting into a dataframe
sp500 = pd.DataFrame(get_sp500)
sp500 = sp500.droplevel('Ticker',axis=1)
sp500 = sp500.drop(['Volume'],axis=1)
sp500.to_csv('SP500.csv')
sp500.head()

Price            Close        High         Low        Open
Date
1985-01-02  165.369995  167.199997  165.190002  167.199997
1985-01-03  164.570007  166.110001  164.380005  165.369995
1985-01-04  163.679993  164.550003  163.360001  164.550003
1985-01-07  164.240005  164.710007  163.679993  163.679993
1985-01-08  163.990005  164.589996  163.910004  164.240005

In [31]:
#Downloading DXY
get_dxy = yf.download('DX-Y.NYB', start='1970-01-01')

[*********************100%***********************]  1 of 1 completed

In [ ]:
#Cleaning data and getting into a dataframe
dxy = pd.DataFrame(get_dxy)
dxy = dxy.droplevel('Ticker',axis=1)
dxy = dxy.drop(['Volume'],axis=1)
dxy.to_csv('DXY.csv')
dxy.head()

Price            Close        High         Low        Open
Date
1971-01-04  120.529999  120.529999  120.529999  120.529999
1971-01-05  120.519997  120.519997  120.519997  120.519997
1971-01-06  120.489998  120.489998  120.489998  120.489998
1971-01-07  120.550003  120.550003  120.550003  120.550003
1971-01-08  120.529999  120.529999  120.529999  120.529999

In [34]:
#Downloading vix
get_vix = yf.download('^VIX', start='1990-01-01')

[*********************100%***********************]  1 of 1 completed

In [35]:
vix = pd.DataFrame(get_dxy)
vix = vix.droplevel('Ticker',axis=1)
vix = vix.drop(['Volume'],axis=1)
vix.to_csv('VIX.csv')
vix.head()

Price            Close        High         Low        Open
Date
1971-01-04  120.529999  120.529999  120.529999  120.529999
1971-01-05  120.519997  120.519997  120.519997  120.519997
1971-01-06  120.489998  120.489998  120.489998  120.489998
1971-01-07  120.550003  120.550003  120.550003  120.550003
1971-01-08  120.529999  120.529999  120.529999  120.529999