In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [16]:
#bdi = broad dollar index
bdi = pd.read_csv('DTWEXBGS.csv')
bdi = bdi.rename(columns={'observation_date':'Date', 'DTWEXBGS':'Close'})
bdi = bdi.set_index('Date')
bdi.head()

               Close
Date
2021-06-18  113.0408
2021-06-21  112.8391
2021-06-22  112.9174
2021-06-23  112.3819
2021-06-24  112.3260

In [12]:
sp500 = pd.read_csv('SP500.csv')
sp500 = sp500.rename(columns={'observation_date':'Date','SP500':'Close'})
sp500 = sp500.set_index('Date')
sp500.head()

              Close
Date
2021-06-18  4166.45
2021-06-21  4224.79
2021-06-22  4246.44
2021-06-23  4241.84
2021-06-24  4266.49

In [13]:
vix = pd.read_csv('VIXCLS.csv')
vix = vix.rename(columns={'observation_date':'Date','VIXCLS':'Close'})
vix = vix.set_index('Date')
vix.head()

            Close
Date
2021-06-21  17.89
2021-06-22  16.66
2021-06-23  16.32
2021-06-24  15.97
2021-06-25  15.62